[package]
name = "v2"
version = "0.1.0"
authors = ["Oliver Snowden <oliversnowden@snodnipper.co.uk>"]

[dependencies]
proj = "0.5.0"
geo-types = "0.1.1"
assert_approx_eq = "1.0.0"
text_io = "0.1.7"
regex = "1.0.2"

#lazy_static = "1.1.0"